Add make parameter to delete the local kind cluster
sustainable-computing-io/local-dev-cluster pull request #11
Opened 2023-05-29 15:29 UTC by jiere

Current Kepler Makefile has `cluster-up`/`cluster-clean`/`cluster-sync`/`cluster-deploy` make targets to manipulate local kind clusters, but lack of cluster destroy operation.
While in local-dev-cluster repo's kind/common.sh, already defined `down()` function, which could implement the kind cluster delete feature.

In current proposed [Platform Validation enhancement](https://github.com/sustainable-computing-io/kepler/pull/711), the test script should support basic setup(kind create cluster) and cleanup(kind delete cluster) ops.

So I am raising this PR along with the above PR to support `make cluster-down` option in Kepler.

2023-05-29 17:59 UTC, rootfs commented
see also #10

2023-05-30 10:11 UTC, marceloamaral approved these changes
/lgtm

2023-05-30 10:12 UTC, marceloamaral commented
@jiere we don't have a way to redo the test.
Can you please an amend commit and force push?

2023-05-30 14:42 UTC, SamYuan1990 requested changes
Please allow me request change to fix CI.

2023-05-31 13:43 UTC, jiere commented
Folks, thanks for all of your comments, I have added my comments in #10, I would suggest to let it in and close this one.

2023-05-31 13:44 UTC, rootfs commented
sounds good @jiere

2023-05-31 13:44 UTC, closed without merging